version: '3'

networks:
  go-network:
    driver: bridge

services:
  db:
    image: mysql:8.0.30-debian
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    tty: true
    volumes:
      - .docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: routes_db
    networks:
      - go-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - go-network

  routes:
    build:
      context: .
    command: "go run main.go"
    ports:
      - "8080:8080"
    container_name: routes
    depends_on:
      - db
    networks:
      - go-network
