// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
)

type Route struct {
	ID             int32
	Name           sql.NullString
	SourceLat      sql.NullString
	SourceLng      sql.NullString
	DestinationLat sql.NullString
	DestinationLng sql.NullString
}
